# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Send notification

on:
  push:
    branches: [ main ]
  schedule:
  - cron: "0 */1 * * *"

jobs:
  publish-pricing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm install
      - run: node index.js
        env:
          BSC_ADDRESS: ${{secrets.BSC_ADDRESS}}
          LINE_AUTHORIZATION: ${{secrets.LINE_AUTHORIZATION}}
